// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote():Promise<main.Note>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetAllTags():Promise<Record<string, number>>;

export function GetNote(arg1:string):Promise<main.Note>;

export function GetNotesByTag(arg1:string):Promise<Array<main.Note>>;

export function GetNotesDir():Promise<string>;

export function ListNotes():Promise<Array<main.Note>>;

export function SaveNote(arg1:main.Note):Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<main.Note>>;

export function SetNotesDir(arg1:string):Promise<void>;

export function StartWatcher():Promise<void>;

export function StopWatcher():Promise<void>;
