// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote() {
  return window['go']['main']['App']['CreateNote']();
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotesByTag(arg1) {
  return window['go']['main']['App']['GetNotesByTag'](arg1);
}

export function GetNotesDir() {
  return window['go']['main']['App']['GetNotesDir']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SetNotesDir(arg1) {
  return window['go']['main']['App']['SetNotesDir'](arg1);
}
